{{- if .Values.certificates.selfSigned }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certificates.rootCA.secretName | default (printf "%s-rootca-certificate" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificates
type: Opaque
data:
  ca.crt: {{ .Values.certificates.rootCA.certificate | default "" | b64enc }}
{{- end }}